{
 "title": "WeRedis Cluster Dashboard",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(job)" },
   {
    "name": "host",
    "query": "label_values(partition_node_status{job=\"$cluster\"},  host)"
   },
   {
    "name": "partition",
    "query": "label_values(partition_node_status{job=\"$cluster\"}, partition)"
   },
   { "name": "port", "query": "label_values(host)" },
   { "name": "ip", "query": "label_values(host)" },
   {
    "name": "master_ip",
    "query": "label_values(redis_slave_repl_offset{host=\"$host\", job=\"$cluster\"}, master_host)"
   },
   {
    "name": "master_port",
    "query": "label_values(redis_slave_repl_offset{host=\"$host\", job=\"$cluster\"}, master_port)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{host=~\"$host\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{host=~\"$host\"}  / redis_memory_max_bytes{host=~\"$host\"} )"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "partition_node_status{job=~\"$cluster\"}"
    },
    {
     "expr": "redis_master_link_up{job=~\"$cluster\"}"
    },
    {
     "expr": "redis_aof_last_write_status{job=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{host=~\"$host\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{host=~\"$host\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{host=~\"$host\"}[1m])"
    }
   ]
  },
  {
   "title": "主从同步延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_master_repl_offset{host=~\"${master_ip}:${master_port}\"} - ignoring(master_host, master_port, host) redis_slave_repl_offset{host=~\"$host\"}",
     "legendFormat": "Repl offset"
    },
    {
     "expr": "redis_master_last_io_seconds_ago{host=~\"$host\"}",
     "legendFormat": "master_last_io_seconds_ago"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{host=~\"$host\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{host=~\"$host\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "内存碎片率",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{host=~\"$host\"}[5m])",
     "legendFormat": "input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{host=~\"$host\"}[5m])",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{host=~\"$host\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{host=~\"$host\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{host =~ \"$host\"}[1m])) by (cmd)\n  /\nsum(irate(redis_commands_total{host =~ \"$host\"}[1m])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{host=~\"$host\"}[1m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{host=~\"$host\"}) - sum (redis_db_keys_expiring{host=~\"$host\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{host=~\"$host\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{host=~\"$host\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{host=~\"$host\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{host=~\"$host\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(redis_blocked_clients{host=~\"$host\"})",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "slow log",
   "type": "graph",
   "description": "slow log对列增长情况",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(redis_slowlog_length{host=~\"$host\"}[1m])"
    }
   ]
  }
 ]
}